services:
  web:
    build: .
    ports:
      - "8092:8091"
    environment:
      - SECRET_KEY=your_secret_key
      - DATABASE_URL=postgresql://user:password@db:5432/attendance
    depends_on:
      - db
    networks:
      - net

  db:
    image: postgres:13
    volumes:
      - /home/cloud_user/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=attendance
    networks:
      - net

networks:
  net:
